name: Github to Jira Automation

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test-transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: https://pulkitsamrat.atlassian.net
        JIRA_USER_EMAIL: pulkit155rkgit@gmail.com 
        JIRA_API_TOKEN: 1Gg7NPdC9wgBQtAIpKJDB486
        
        
    - name: Transition issue
      uses: atlassian/gajira-transition@master 
      with:
        issue: ${{ github.head_ref }}
        transition: "In progress"  
        
        
    - name: Transition issue not roll back
      uses: atlassian/gajira-transition@master
      with:
       if: github.event_name == 'pull_request' || github.event.action == 'opened
       issue: ${{ github.head_ref }}
       more-transition: "To Do"
       required: false

    # - name: Jira find and transition issues
    #   uses: bloobirds-it/action-transition-multiple-jira-issues@v1.1.0
    #   with:
    #     jira-base-url: https://<yourdomain>.atlassian.net
    #     jira-user-email: human@example.com
    #     jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     target-status: In Progress
   

    # - name: Jira find and transition issues
    #   uses: chontawee/gj-find-transition-issues@1.0.4
    #   with:
    #     issuetypes: Task,Bug
    #     transitions: In Progress,To Do
