name: Github to Jira Automation

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test-transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_REST_API }}
        
        
    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ github.head_ref }}
        transition: "In progress"


    # - name: Jira find and transition issues
    #   uses: bloobirds-it/action-transition-multiple-jira-issues@v1.1.0
    #   with:
    #     jira-base-url: https://<yourdomain>.atlassian.net
    #     jira-user-email: human@example.com
    #     jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     target-status: In Progress
    #     issue-prefixes: BB, P1
    #     ignore-statuses: Done, QA    

    # - name: Jira find and transition issues
    #   uses: chontawee/gj-find-transition-issues@1.0.4
    #   with:
    #     issuetypes: Task,Bug
    #     transitions: In Progress,To Do
